const db = require('../config/database');
const { ensureSatisfactionTable } = require('../services/satisfactionService');
const { FIXED_COST } = require('../services/costConfig');

const PAGE = { width: 612, height: 792, margin: 44 };
const COLORS = {
  ink: '0.11 0.16 0.22',
  muted: '0.40 0.45 0.52',
  line: '0.78 0.82 0.88',
  panel: '0.96 0.97 0.99',
  header: '0.08 0.16 0.28',
  accent: '0.05 0.37 0.58',
  white: '1 1 1',
};

const formatDate = (value) => {
  if (!value) return '';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return String(value);
  return date.toLocaleString('en-GB', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    hour12: false,
  });
};

const number = (value, digits = 1) => {
  const n = parseFloat(value);
  return Number.isFinite(n) ? n.toFixed(digits) : '';
};

const money = (value) => {
  const n = parseFloat(value);
  return Number.isFinite(n) ? `${n.toFixed(2)} EUR` : '';
};

const percent = (value) => {
  const n = parseFloat(value);
  return Number.isFinite(n) ? `${n.toFixed(1)}%` : '';
};

const display = (value, fallback = 'Not available') => {
  if (value === null || value === undefined || value === '') return fallback;
  if (typeof value === 'boolean') return value ? 'Yes' : 'No';
  return String(value);
};

const normalizeForPdf = (text) => display(text, '')
  .normalize('NFKD')
  .replace(/[\u0300-\u036f]/g, '')
  .replace(/[^\x09\x0A\x0D\x20-\x7E]/g, char => {
    const replacements = {
      '€': 'EUR',
      '°': ' deg',
      '²': '2',
      '³': '3',
      'µ': 'u',
      '×': 'x',
      '–': '-',
      '—': '-',
      '’': "'",
      '“': '"',
      '”': '"',
      '•': '-',
      '→': '->',
    };
    return replacements[char] || ' ';
  });

const toPdfText = (text) => {
  const input = normalizeForPdf(text);
  return `(${input.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)')})`;
};

const wrapText = (text, maxChars = 92) => {
  const raw = normalizeForPdf(text).replace(/\r/g, '').split('\n');
  const lines = [];
  raw.forEach(part => {
    const words = part.trim().split(/\s+/).filter(Boolean);
    if (words.length === 0) {
      lines.push('');
      return;
    }
    let line = '';
    words.forEach(word => {
      const next = line ? `${line} ${word}` : word;
      if (next.length > maxChars && line) {
        lines.push(line);
        line = word;
      } else {
        line = next;
      }
    });
    if (line) lines.push(line);
  });
  return lines;
};

const actualPrintHours = (startTime, endTime) => {
  if (!startTime || !endTime) return null;
  const start = new Date(startTime);
  const end = new Date(endTime);
  const hours = (end.getTime() - start.getTime()) / 3600000;
  return Number.isFinite(hours) && hours >= 0 ? hours : null;
};

const buildSummary = (request, cycles) => {
  const actual = parseFloat(request.actual_cost || 0);
  const reworkCycles = cycles.slice(1);
  const fixedCost = (cycles.length > 0 || actual > 0) ? FIXED_COST : 0;

  return {
    actual,
    fixedCost,
    reworkCount: reworkCycles.length,
    reworkMaterial: reworkCycles.reduce((sum, c) => sum + parseFloat(c.material_used || 0), 0),
    reworkCost: reworkCycles.reduce((sum, c) => sum + parseFloat(c.actual_cost || 0), 0),
  };
};

const createPdf = ({ request, generatedBy, history, attachments, cycles, satisfaction }) => {
  const pages = [];
  let commands = [];
  let y = PAGE.height - PAGE.margin;
  let pageNumber = 0;
  const generatedAt = new Date();
  const summary = buildSummary(request, cycles);

  const raw = (cmd) => commands.push(cmd);
  const setColor = (color = COLORS.ink) => raw(`${color} rg ${color} RG`);
  const rect = (x, yy, w, h, { fill = false, stroke = true, color = COLORS.line } = {}) => {
    setColor(color);
    raw(`${x} ${yy} ${w} ${h} re ${fill && stroke ? 'B' : fill ? 'f' : 'S'}`);
    setColor(COLORS.ink);
  };

  const text = (value, x, yy, { size = 9, font = 'F1', color = COLORS.ink } = {}) => {
    setColor(color);
    raw(`BT /${font} ${size} Tf ${x} ${yy} Td ${toPdfText(value)} Tj ET`);
    setColor(COLORS.ink);
  };

  const footer = () => {
    rect(PAGE.margin, 34, PAGE.width - PAGE.margin * 2, 0.5, { color: COLORS.line });
    text('Generated by: 3D Printing Request Management System', PAGE.margin, 22, { size: 7, color: COLORS.muted });
    text(`Generation Date: ${formatDate(generatedAt)}`, 260, 22, { size: 7, color: COLORS.muted });
    text(`Page ${pageNumber}`, 530, 22, { size: 7, color: COLORS.muted });
  };

  const startPage = () => {
    if (commands.length) {
      footer();
      pages.push(commands.join('\n'));
    }
    commands = [];
    pageNumber += 1;
    y = PAGE.height - PAGE.margin;
  };

  const ensure = (height) => {
    if (y - height < 58) startPage();
  };

  startPage();

  const addHeader = () => {
    rect(PAGE.margin, y - 78, PAGE.width - PAGE.margin * 2, 78, { fill: true, stroke: false, color: COLORS.header });
    rect(PAGE.margin + 14, y - 58, 72, 36, { fill: false, stroke: true, color: COLORS.white });
    text('AVO', PAGE.margin + 28, y - 39, { size: 14, font: 'F2', color: COLORS.white });
    text('CARBON', PAGE.margin + 51, y - 39, { size: 8, font: 'F2', color: COLORS.white });
    text('3D Printing Request Report', PAGE.margin + 104, y - 28, { size: 18, font: 'F2', color: COLORS.white });
    text(`Request ID: ${display(request.request_number)}`, PAGE.margin + 104, y - 47, { size: 10, color: COLORS.white });
    text(`Status: ${display(request.status)}`, PAGE.margin + 104, y - 62, { size: 9, color: COLORS.white });
    text(`Generated: ${formatDate(generatedAt)}`, 430, y - 30, { size: 8, color: COLORS.white });
    text(`Generated By: ${display(generatedBy)}`, 430, y - 45, { size: 8, color: COLORS.white });
    text(`Site: ${display(request.site_name)}`, 430, y - 60, { size: 8, color: COLORS.white });
    y -= 100;
  };

  const sectionTitle = (title) => {
    ensure(32);
    text(title, PAGE.margin, y, { size: 12, font: 'F2', color: COLORS.accent });
    rect(PAGE.margin, y - 7, PAGE.width - PAGE.margin * 2, 0.6, { color: COLORS.line });
    y -= 22;
  };

  const keyValueGrid = (rows) => {
    const leftX = PAGE.margin;
    const rightX = 318;
    const labelW = 104;
    for (let i = 0; i < rows.length; i += 2) {
      ensure(22);
      [rows[i], rows[i + 1]].filter(Boolean).forEach((row, columnIndex) => {
        const x = columnIndex === 0 ? leftX : rightX;
        text(row[0], x, y, { size: 7, font: 'F2', color: COLORS.muted });
        wrapText(row[1], 33).slice(0, 2).forEach((line, lineIndex) => {
          text(line, x + labelW, y - (lineIndex * 10), { size: 8 });
        });
      });
      y -= 22;
    }
    y -= 6;
  };

  const paragraph = (value) => {
    const lines = wrapText(value || 'Not available', 104);
    lines.forEach(line => {
      ensure(13);
      text(line, PAGE.margin, y, { size: 8 });
      y -= 12;
    });
    y -= 6;
  };

  const table = (headers, rows, widths) => {
    const rowHeight = 18;
    const totalWidth = widths.reduce((sum, w) => sum + w, 0);
    ensure(rowHeight * 2);
    rect(PAGE.margin, y - rowHeight + 4, totalWidth, rowHeight, { fill: true, stroke: false, color: COLORS.panel });
    let x = PAGE.margin + 4;
    headers.forEach((header, i) => {
      text(header, x, y - 8, { size: 7, font: 'F2', color: COLORS.muted });
      x += widths[i];
    });
    y -= rowHeight;

    if (!rows.length) rows = [[
      'No data available',
      ...headers.slice(1).map(() => ''),
    ]];
    rows.forEach(row => {
      const wrapped = row.map((cell, i) => wrapText(cell, Math.max(10, Math.floor(widths[i] / 5.2))).slice(0, 3));
      const height = Math.max(rowHeight, Math.max(...wrapped.map(lines => lines.length)) * 10 + 8);
      ensure(height + 2);
      rect(PAGE.margin, y - height + 4, totalWidth, height, { stroke: true, color: COLORS.line });
      let cellX = PAGE.margin + 4;
      wrapped.forEach((lines, i) => {
        lines.forEach((line, lineIndex) => text(line, cellX, y - 8 - lineIndex * 10, { size: 7.5 }));
        cellX += widths[i];
      });
      y -= height;
    });
    y -= 12;
  };

  addHeader();

  sectionTitle('1. Request Information');
  keyValueGrid([
    ['Request ID', request.request_number],
    ['Title', request.title],
    ['Requester', request.requester_full_name || request.requester_name],
    ['Department', request.requester_department || request.requester_user_department],
    ['Site', request.site_name],
    ['Category', request.category_name],
    ['Priority', request.priority],
    ['Requested Qty', request.quantity],
    ['Due Date', formatDate(request.requested_due_date || request.approved_due_date)],
    ['Creation Date', formatDate(request.created_at)],
  ]);

  sectionTitle('2. Request Description');
  paragraph(`Purpose:\n${display(request.purpose)}`);
  paragraph(`Part Description:\n${display(request.part_description)}`);
  paragraph(`Business Justification:\n${display(request.business_impact || request.priority_reason)}`);
  paragraph(`Special Requirements:\n${[
    request.functional_requirement && `Functional: ${request.functional_requirement}`,
    request.visual_requirement && `Visual: ${request.visual_requirement}`,
    request.strength_requirement && `Strength: ${request.strength_requirement}`,
    request.surface_finish && `Surface Finish: ${request.surface_finish}`,
    request.tolerance && `Tolerance: ${request.tolerance}`,
  ].filter(Boolean).join('\n') || 'Not available'}`);

  startPage();
  sectionTitle('3. Workflow Summary');
  keyValueGrid([
    ['Current Status', request.status],
    ['Approval Date', formatDate(request.approved_at)],
    ['Completion Date', formatDate(request.completion_date)],
    ['Technician', request.technician_full_name],
    ['Printer', request.printer_name],
    ['Manager/Production', request.qc_approved_by_name],
  ]);

  sectionTitle('4. Workflow History');
  table(
    ['Date/Time', 'User', 'Transition', 'Comment'],
    history.map(h => [
      formatDate(h.created_at),
      h.changed_by_name || 'Unknown',
      `${h.from_status || 'Start'} -> ${h.to_status}`,
      h.comment || '',
    ]),
    [108, 118, 134, 208]
  );

  sectionTitle('5. Planning Information');
  const plannedHours = actualPrintHours(request.planned_start_date, request.planned_end_date);
  keyValueGrid([
    ['Planned Start', formatDate(request.planned_start_date)],
    ['Planned End', formatDate(request.planned_end_date)],
    ['Planned Duration', plannedHours !== null ? `${number(plannedHours, 2)} h` : 'Not available'],
    ['Reserved Qty', request.material_reserved_qty ? `${number(request.material_reserved_qty, 1)} g` : 'Not available'],
    ['Material', request.material_name],
    ['Printer', request.printer_name],
    ['Price', request.price_per_kg ? `${number(request.price_per_kg, 2)} EUR/kg or EUR/L` : 'Not available'],
    ['Batch Reference', request.batch_reference],
  ]);

  sectionTitle('6. Production Information');
  const printHours = actualPrintHours(request.actual_start_time, request.actual_end_time);
  keyValueGrid([
    ['Printed Qty', request.printed_quantity],
    ['Material Used', request.material_used_grams ? `${number(request.material_used_grams, 1)} g` : 'Not available'],
    ['Actual Print Time', printHours !== null ? `${number(printHours, 2)} h` : 'Not available'],
    ['Start Time', formatDate(request.actual_start_time)],
    ['End Time', formatDate(request.actual_end_time)],
    ['Duration', printHours !== null ? `${number(printHours, 2)} h` : 'Not available'],
  ]);
  table(
    ['Cycle', 'Printed', 'Rejected', 'Material', 'Cost', 'Start', 'End'],
    cycles.map(c => [
      c.cycle_number,
      c.printed_quantity,
      c.rejected_quantity,
      `${number(c.material_used, 1)} g`,
      money(c.actual_cost),
      formatDate(c.start_time),
      formatDate(c.end_time),
    ]),
    [46, 58, 58, 76, 76, 126, 126]
  );

  startPage();
  sectionTitle('7. Cost Information');
  keyValueGrid([
    ['Actual Cost', money(summary.actual)],
    ['Rework Count', summary.reworkCount],
    ['Rework Material', summary.reworkCount ? `${number(summary.reworkMaterial, 1)} g` : '0.0 g'],
    ['Rework Cost', summary.reworkCount ? money(summary.reworkCost) : '0.00 EUR'],
    ['Fixed Cost', money(summary.fixedCost)],
    ['Fixed Cost Formula', `(Material Weight x Material Rate) + (Print Time x Time Rate) + ${number(FIXED_COST, 2)} EUR`],
  ]);

  sectionTitle('8. Quality Control');
  keyValueGrid([
    ['QC Result', request.quality_result],
    ['Technician Notes', request.quality_notes],
    ['Rejection Reason', request.rejection_reason],
    ['Rework Required', request.rework_required],
    ['Rework Reason', request.rework_reason],
    ['Scrap / Failed', request.scrap_count],
  ]);

  sectionTitle('9. Requester Confirmation');
  if (request.requester_confirmation || request.reception_confirmed_at) {
    keyValueGrid([
      ['Confirmation Date', formatDate(request.reception_confirmed_at || request.completion_date)],
      ['Requester Name', request.reception_confirmed_by || request.requester_full_name || request.requester_name],
      ['Satisfaction', satisfaction?.overall_rating ? `${satisfaction.overall_rating} / 5` : 'Not submitted'],
      ['Comment', request.reception_comment],
      ['Condition', request.reception_condition],
    ]);
  } else {
    paragraph('Pending Confirmation');
  }

  sectionTitle('10. Requester Feedback');
  if (satisfaction) {
    keyValueGrid([
      ['Overall Satisfaction', `${satisfaction.overall_rating} / 5`],
      ['Part Quality', `${satisfaction.quality_rating} / 5`],
      ['Delivery Time', `${satisfaction.delivery_rating} / 5`],
      ['Communication', `${satisfaction.communication_rating} / 5`],
      ['Fulfillment', satisfaction.fulfillment_result],
      ['Recommendation', satisfaction.recommendation_score],
      ['Submission Date', formatDate(satisfaction.created_at)],
    ]);
    paragraph(`Requester Comment:\n${display(satisfaction.comment)}`);
  } else {
    paragraph('No satisfaction survey submitted.');
  }

  sectionTitle('11. Attachments');
  table(
    ['Filename', 'Upload Date', 'Uploaded By'],
    attachments.map(a => [
      a.original_name,
      formatDate(a.uploaded_at),
      a.uploaded_by_name || 'Unknown',
    ]),
    [270, 128, 170]
  );

  if (commands.length) {
    footer();
    pages.push(commands.join('\n'));
  }

  const objects = [];
  const addObject = (body) => {
    objects.push(body);
    return objects.length;
  };

  const fontRegular = addObject('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');
  const fontBold = addObject('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>');
  const pageRefs = [];

  pages.forEach(content => {
    const contentRef = addObject(`<< /Length ${Buffer.byteLength(content, 'utf8')} >>\nstream\n${content}\nendstream`);
    const pageRef = addObject(`<< /Type /Page /Parent PAGES_REF 0 R /MediaBox [0 0 ${PAGE.width} ${PAGE.height}] /Resources << /Font << /F1 ${fontRegular} 0 R /F2 ${fontBold} 0 R >> >> /Contents ${contentRef} 0 R >>`);
    pageRefs.push(pageRef);
  });

  const pagesRef = addObject(`<< /Type /Pages /Kids [${pageRefs.map(ref => `${ref} 0 R`).join(' ')}] /Count ${pageRefs.length} >>`);
  const catalogRef = addObject(`<< /Type /Catalog /Pages ${pagesRef} 0 R >>`);

  let pdf = '%PDF-1.4\n';
  const offsets = [0];
  objects.forEach((body, index) => {
    offsets.push(Buffer.byteLength(pdf, 'utf8'));
    pdf += `${index + 1} 0 obj\n${body.replace(/PAGES_REF/g, String(pagesRef))}\nendobj\n`;
  });
  const xrefOffset = Buffer.byteLength(pdf, 'utf8');
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  offsets.slice(1).forEach(offset => {
    pdf += `${String(offset).padStart(10, '0')} 00000 n \n`;
  });
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root ${catalogRef} 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  return Buffer.from(pdf, 'utf8');
};

exports.downloadRequestPdf = async (req, res) => {
  try {
    const { id } = req.params;

    const requestResult = await db.query(`
      SELECT r.*,
        u.first_name || ' ' || u.last_name AS requester_full_name,
        u.email AS requester_email,
        u.department AS requester_user_department,
        t.first_name || ' ' || t.last_name AS technician_full_name,
        p.name AS printer_name,
        m.name AS material_name,
        c.name AS category_name,
        s.name AS site_name
      FROM print_requests r
      LEFT JOIN users u ON r.requester_id = u.id
      LEFT JOIN users t ON r.assigned_technician_id = t.id
      LEFT JOIN printers p ON r.printer_id = p.id
      LEFT JOIN materials m ON r.material_id = m.id
      LEFT JOIN request_categories c ON r.category_id = c.id
      LEFT JOIN sites s ON r.site_id = s.id
      WHERE r.id = $1
    `, [id]);

    const request = requestResult.rows[0];
    if (!request) return res.status(404).json({ error: 'Request not found' });

    if (req.user.role === 'requester' && request.requester_id !== req.user.id) {
      return res.status(403).json({ error: 'Access denied' });
    }

    const history = await db.query(
      'SELECT * FROM status_history WHERE request_id = $1 ORDER BY created_at',
      [id]
    );
    const attachments = await db.query(`
      SELECT a.*,
             u.first_name || ' ' || u.last_name AS uploaded_by_name
      FROM request_attachments a
      LEFT JOIN users u ON a.uploaded_by = u.id
      WHERE a.request_id = $1
      ORDER BY a.uploaded_at
    `, [id]);
    const cycles = await db.query(`
      SELECT pc.*,
             u.first_name || ' ' || u.last_name AS created_by_full_name
      FROM request_production_cycles pc
      LEFT JOIN users u ON pc.created_by = u.id
      WHERE pc.request_id = $1
      ORDER BY pc.cycle_number
    `, [id]).catch(() => ({ rows: [] }));
    await ensureSatisfactionTable(db);
    const satisfaction = await db.query(
      'SELECT * FROM request_satisfaction_surveys WHERE request_id = $1',
      [id]
    ).catch(() => ({ rows: [] }));

    const generatedBy = [req.user.first_name, req.user.last_name].filter(Boolean).join(' ')
      || req.user.email
      || req.user.id;
    const pdf = createPdf({
      request,
      generatedBy,
      history: history.rows,
      attachments: attachments.rows,
      cycles: cycles.rows,
      satisfaction: satisfaction.rows[0] || null,
    });
    const filename = `Request_${request.request_number || id}.pdf`;

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    res.setHeader('Content-Length', pdf.length);
    res.send(pdf);
  } catch (err) {
    console.error('[PDF] Request report generation failed:', err);
    res.status(500).json({ error: 'Server error' });
  }
};
